pipeline:
  backend:
    image: microsoft/aspnetcore-build:2.0
    commands:
      - dotnet restore src/PipelineSample.sln
      - dotnet -c Release src/PipelineSample.sln

  notify:
    image: plugins/slack
    channel: developers
    username: drone