queue:
  name: API Enablement
  demands: OS -equals Linux
name: $(Build.BuildId)
trigger:
- master
steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: 'src/PipelineSample.sln'
    verbosityRestore: Quiet
  enabled: false

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: 'src/PipelineSample.sln'
    arguments: '-c Release'
  enabled: false

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: 'src/PipelineSample.WebApi.Tests/PipelineSample.WebApi.Tests.csproj'
  enabled: false

- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/PipelineSample.WebApi/PipelineSample.WebApi.csproj'
    arguments: '-c Release -o $(Build.SourcesDirectory)/output'
    zipAfterPublish: false
    modifyOutputPath: false
  enabled: false

- task: Docker@0
  displayName: Build an image
  inputs:
    containerregistrytype: 'Container Registry'
    dockerFile: Dockerfile
    imageName: 'pipelinesample:$(Build.BuildId)'
    qualifyImageName: false
  enabled: false

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  displayName: 'Push Image:'
  inputs:
    awsCredentials: 'Shared ECR Non-Prod'
    regionName: 'eu-central-1'
    sourceImageName: pipelinesample
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: 'dfds/pipelinesample'
    pushTag: '$(Build.BuildId)'
    autoCreateRepository: true
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: manifests'
  inputs:
    PathtoPublish: k8s
    ArtifactName: manifests
  enabled: false

- bash: |
   export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
   chmod +x ./pipeline.sh
   ./pipeline.sh $(Build.BuildId)
  displayName: Pipeline Bash Script
  enabled: true

- powershell: |
   $env:AWS_SECRET_ACCESS_KEY = "$(AWS_SECRET_ACCESS_KEY)"
   ./pipeline.ps1 -pushImage -buildNumber $(Build.BuildId)
  displayName: Pipeline PowerShell Script
  enabled: false

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: testresult.trx
    searchFolder: '$(System.DefaultWorkingDirectory)/src'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: manifests"
  inputs:
    PathtoPublish: k8s
    ArtifactName: manifests